# Generated by Django 4.2.11 on 2024-05-05 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('functionality', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalperformance',
            old_name='vendor',
            new_name='vendor_code',
        ),
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='vendor',
            new_name='vendor_code',
        ),
    ]
