# Generated by Django 4.2.11 on 2024-05-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functionality', '0003_rename_vendor_code_historicalperformance_vendor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_number',
            field=models.IntegerField(max_length=50, unique=True),
        ),
    ]
